name: siprok_appointments
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  # cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  get: ^4.6.5
  sidebarx: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter  
  lint: ^1.10.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logos/
